BE/accounts/urls.py
from django.urls import path
from accounts.views import signup_view, login_view, logout_view
from .api import AuthAPI , SignupAPI , RetrieveUserAPI , AccountDeleteAPI , LogoutAPI
from rest_framework_simplejwt.views import TokenRefreshView

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    #api
    path('api/retrieveuser/',RetrieveUserAPI.as_view()),#유저 개별 조회
    path('api/signup/',SignupAPI.as_view()), #회원가입
    path("api/auth/",AuthAPI.as_view()), # 로그인
    path("api/logout/",LogoutAPI.as_view()),#로그아웃
    path("api/userdelete/",AccountDeleteAPI.as_view()), #회원탈퇴
    path("api/auth/refresh/",TokenRefreshView.as_view()), #jwt 토큰 재발급
]

BE/birthday_cake/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import main_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_view, name='main'),
    path('accounts/', include('accounts.urls')),
    path('cakes/', include('cakes.urls')),
    path('contacts/', include('contacts.urls')),

    path('users/',include('accounts.urls')),
]

BE/cakes/urls.py
from django.urls import path
from cakes.views import myroom_own , cake_custom ,myroom_visitor,message_open,create_message

from .api import CreateMessageAPI , DeleteMessageAPI , MessageListAPI , MessageRetieve , CakeCustomAPI ,CakeGetAPI , CakeGetVisitAPI , MessageCountAPI_owner , MessageCountAPI_visit

app_name = 'cakes'

urlpatterns = [
    path('ownroom/<int:user_id>/',myroom_own,name='ownroom'),
    path('cakecustom/<int:user_id>/',cake_custom,name='cakemaker'),
    path('visit/<int:user_id>/',myroom_visitor,name='visitor'),
    path('message_open/<int:user_id>/',message_open,name='message_open'),
    path('createmessage/<int:user_id>/',create_message,name='messagemaker'),

    #api
    path('api/createmessage/<str:user_name>/',CreateMessageAPI.as_view()), #메시지작성
    path('api/deletemessage/<int:message_id>/',DeleteMessageAPI.as_view()), #메시지삭제
    path('api/messagelist',MessageListAPI.as_view()), #메시지 리스트 조회
    path('api/messageretrieve/<int:message_id>/',MessageRetieve.as_view()), #메시지 detail 조회 
    path('api/cake-custom/',CakeCustomAPI.as_view()), #케이크 디자인 변경
    path('api/getcake/',CakeGetAPI.as_view()), #케이크 디자인 조회 (owner)
    path('api/getcakevisit/<str:owner_username>/',CakeGetVisitAPI.as_view()), #케이크 디자인 조회 (visit)
    path('api/messagecount_owner/',MessageCountAPI_owner.as_view()), #받은 메시지 갯수 조회 (owner)
    path('api/messagecount_visit/<str:user_name>/',MessageCountAPI_visit.as_view()), #받은 메시지 갯수 조회 (visit)
    ]

BE/contacts/urls.py
from django.urls import path
from . import views
from .api import FriendAddAPI , FriendListAPI , FriendDeleteAPI

app_name = 'contacts'

urlpatterns = [
    path('', views.contact_list, name='contact_list'),  # 친구 목록 페이지
    path('add/', views.add_contact, name='add_contact'), # 친구 추가 페이지

    #api
    path('api/add-friend/',FriendAddAPI.as_view()), #친구추가 API   
    path('api/friends-list/',FriendListAPI.as_view()), #친구 리스트 조회 API
    path('api/delete-friend/<int:friend_id>',FriendDeleteAPI.as_view()) #친구삭제 API
]

BE/cakes/models.py
from django.db import models
from accounts.models import CustomUser
# Create your models here.

class message (models.Model):
    party = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    message_content = models.TextField()
    background = models.IntegerField(default=0)
    sent_by = models.CharField(max_length=225)
    font = models.IntegerField(default=0)
    matrix = models.IntegerField(default=0)

class cake_custom (models.Model):
    party = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    base = models.IntegerField(default=0)
    light= models.IntegerField(default=0)

    deco1 = models.IntegerField(default=0)
    deco2 = models.IntegerField(default=0)
    deco3 = models.IntegerField(default=0)
    deco4 = models.IntegerField(default=0)
    deco5 = models.IntegerField(default=0)
    deco6 = models.IntegerField(default=0)
    deco7 = models.IntegerField(default=0)
    deco8 = models.IntegerField(default=0)
    deco9 = models.IntegerField(default=0)
    deco10 = models.IntegerField(default=0)
    deco11 = models.IntegerField(default=0)
    

BE/cakes/forms.py
from django import forms
from .models import message

class MessageForm(forms.ModelForm):
    class Meta:
        model = message
        fields = ['message_content']
        labels={
            'message_content' : '내용'
        }

BE/cakes/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib.auth import get_user_model
from datetime import date
from .forms import MessageForm

@login_required
def myroom_own (request,user_id): 
    User = get_user_model()
    owner = User.objects.get(id=user_id)
    birthday = owner.birthday

    if birthday != date.today() :
        today = date.today()
        this_year_birthday = birthday.replace(year=today.year)

        if this_year_birthday < today:
            next_year_birthday = birthday.replace(year=today.year+1)
            d_day = (next_year_birthday - today).days
        else:
            d_day = (this_year_birthday - today).days
        
        birthday = birthday.strftime('%m월 %d일')

        context={
            'owner':owner, 
            'birthday':birthday,
            'd_day':d_day,
            }
        return render (request,'myroom/room_own.html',context)
    
    else:
        context={
        'owner':owner, 
        'birthday':birthday,
        }
    return render (request,'myroom/room_own_Dday.html',context)

def myroom_visitor (request,user_id):
    User = get_user_model()
    owner = User.objects.get(id=user_id)
    birthday = owner.birthday

    if birthday != date.today() :
        today = date.today()
        this_year_birthday = birthday.replace(year=today.year)

        if this_year_birthday < today:
            next_year_birthday = birthday.replace(year=today.year+1)
            d_day = (next_year_birthday - today).days
        else:
            d_day = (this_year_birthday - today).days
        
        birthday = birthday.strftime('%m월 %d일')

        context={
            'owner':owner, 
            'birthday':birthday,
            'd_day':d_day,
            }
        return render (request,'myroom/room_visitor.html',context)
    
    else:
        context={
        'owner':owner, 
        'birthday':birthday,
        }
    return render (request,'myroom/room_visitor_Dday.html',context)

def cake_custom (request,user_id):
    User = get_user_model()
    owner = User.objects.get(id=user_id)
    context = {
        'owner' : owner
    }
    return render (request,'myroom/cakemaker.html',context)

def message_open (request,user_id):
    User = get_user_model()
    owner = User.objects.get(id=user_id)
    context = {
        'owner' : owner
    }
    return render(request,'myroom/message_open.html',context)

def create_message (request,user_id):
    User = get_user_model()
    owner = User.objects.get(id=user_id)
    form = MessageForm()
    context = {'form':form,
               'owner':owner}
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.party = owner
            message.save()
            return redirect('cakes:visitor',user_id=owner.id)
    else: 
        return render(request,'myroom/messagemaker.html',context)

BE/cakes/templates/myroom/cakemaker.html
<iframe height='400' width='250'></iframe><br>
<input type='button' value='color'>
<input type='button' value='decoration'>
<input type='button' value='syrup'>
<input type='button' value='save'><br><br>
<a href="{% url 'cakes:ownroom' owner.id %}"><input type='button' value='돌아가기'></a>

BE/cakes/templates/myroom/message_open.html
<h5>{{owner.message_set.count}}개의 메시지가 있습니다.</h5>
<div>
    <ul>
    {% for message in owner.message_set.all %}
        <li>{{ message.message_content }}</li>
    {% endfor %}
    </ul>
</div>

BE/cakes/templates/myroom/messagemaker.html
<form method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <button type='submit'>저장하기</button><br><br>
</form>

BE/cakes/templates/myroom/room_own.html
<body>

    {% if request.user.is_authenticated %}
    <h6> {{owner.username}}님의 파티룸 / birthday:{{birthday}} / D-{{d_day}}</h6>
    <iframe height='400' width='250'></iframe><br><br>
    <a href={% url 'cakes:cakemaker' owner.id %}><input type='button' value='꾸미기'></a><br>
    <button id="copyButton">초대장 공유</button>
    <script>
        document.getElementById('copyButton').addEventListener('click', function() {
            
            const currentUrl = window.location.href;
            const newUrl = currentUrl.replace('/ownroom/', '/visit/');
            const tempInput = document.createElement('input');
            tempInput.value = newUrl;
            document.body.appendChild(tempInput);
            tempInput.select();
            document.execCommand('copy');
            document.body.removeChild(tempInput);
    
            alert('URL이 복사되었습니다: ' + newUrl);
        });
    </script>
    <br> 
    <a href={% url 'contacts:contact_list' %}><input type='button' value='친구목록'></a><br>
    <a href={% url 'cakes:message_open' owner.id %}><input type='button' value='메시지 확인'></a><br><br><br><br>
    <a href={% url 'main' %}><input type='button' value='메인으로'></a>

    {% else %}
    <h3> !로그인이 필요한 서비스 입니다! </h3>
    <a href={% url 'accounts:login' %}><input type='button' value='확인'></a>
    {% endif %}

<body>

BE/cakes/templates/myroom/room_own_Dday.html
<body>

    {% if request.user.is_authenticated %}
    <h6> {{owner.username}}님의 파티룸 / birthday:{{birthday}} / D-day!</h6>
    <iframe height='400' width='250'></iframe><br><br>
    <a href={% url 'cakes:cakemaker' owner.id %}><input type='button' value='꾸미기'></a><br>
    <button id="copyButton">초대장 공유</button>
    <script>
        document.getElementById('copyButton').addEventListener('click', function() {
            const currentUrl = window.location.href;
            const newUrl = currentUrl.replace('/ownroom/', '/visit/');
            const tempInput = document.createElement('input');
            tempInput.value = newUrl;
            document.body.appendChild(tempInput);
            tempInput.select();
            document.execCommand('copy');
            document.body.removeChild(tempInput);
    
            alert('URL이 복사되었습니다: ' + newUrl);
        });
    </script>
    <br> 
    <a href={% url 'contacts:contact_list' %}><input type='button' value='친구목록'></a><br>
    <a href={% url 'cakes:message_open' owner.id %}><input type='button' value='메시지 확인'></a><br><br><br><br>
    <a href={% url 'main' %}><input type='button' value='메인으로'></a>
    {% else %}
    <h3> !로그인이 필요한 서비스 입니다! </h3>
    <a href={% url 'accounts:login' %}><input type='button' value='확인'></a>
    {% endif %}

<body>

BE/cakes/templates/myroom/room_visitor.html
<body>

    {% if request.user.is_authenticated %}
    <h6> {{owner.username}}님의 파티룸 / birthday:{{birthday}} / D-{{d_day}}</h6>
    <iframe height='400' width='250'></iframe><br><br>
    <button onclick="copyCurrentUrl()">초대장 공유</button>
    <script>
        function copyCurrentUrl() {
            const currentUrl = window.location.href;
            const tempInput = document.createElement('input');
            tempInput.value = currentUrl;
            document.body.appendChild(tempInput);
            tempInput.select();
            tempInput.setSelectionRange(0, 99999);

            document.execCommand('copy');

            document.body.removeChild(tempInput);

            alert('초대장 URL이 복사되었습니다: ' + currentUrl);
        } 
    </script><br>
    <a href={% url 'cakes:messagemaker' owner.id  %}><input type='button' value='메시지 작성'></a>

    {% else %}
    <h3> !로그인이 필요한 서비스 입니다! </h3>
    <a href={% url 'accounts:login' %}><input type='button' value='확인'></a>
    {% endif %}

<body>

BE/cakes/templates/myroom/room_visitor_Dday.html
<body>

    {% if request.user.is_authenticated %}
    <h6> {{owner.username}}님의 파티룸 / birthday:{{birthday}} / D-day! </h6>
    <iframe height='400' width='250'></iframe><br><br>
    <button onclick="copyCurrentUrl()">초대장 공유</button>
    <script>
        function copyCurrentUrl() {
            const currentUrl = window.location.href;
            const tempInput = document.createElement('input');
            tempInput.value = currentUrl;
            document.body.appendChild(tempInput);
            tempInput.select();
            tempInput.setSelectionRange(0, 99999);

            document.execCommand('copy');

            document.body.removeChild(tempInput);

            alert('초대장 URL이 복사되었습니다: ' + currentUrl);
        } 
    </script><br> 
    <a href={% url 'cakes:messagemaker' %}><input type='button' value='메시지 작성'></a>
    

    {% else %}
    <h3> !로그인이 필요한 서비스 입니다! </h3>
    <a href={% url 'accounts:login' %}><input type='button' value='확인'></a>
    {% endif %}

<body>